### ISSUE TITLE
Getting to version 1.0 checklist

### ISSUE THREAD

**Issue by damianh** [SQLStreamStore/SQLStreamStore#8]
Outstanding items to get to a v0.1 release:
- [x] Message Metadata - ~~`string` with arbitrary json vs `Dictionary<string, string>`~~ it's just a string you can insert your own json?
- [x] Stream Metadata api - ~~`string` with arbitrary json vs `Dictionary<string, string>`?~~ Special message object with known properties `MaxAge` and `MaxCount` + user json.. Store as independent stream or not? _yes_. Expose via all stream? _yes_ Support `MaxAge` and `MaxCount`
- [x] Steam deletion ~~(support tomb stoning?)~~
- [x] Message deletion
- [x] Scavaging - "Older than X", "Prior to Version Y"
- [x] Rename. A) StreamStore or B) SqlStreamStore
- [x] XML Comment all the public things
- [x] Logging
- [x] ~Performance metrics~ Added a load test project. Perf counters / metrics in a subsequent version.
- [ ] Docs - readthedocs?
- [x] Sample project

Post 0.1 (just noting for now)
- Postgres
- Stream Migration

**Comment by danbarua** [comment]
Schema versioning/migrations?

**Comment by damianh** [comment]
@danbarua I'm looking for suggestions on that. It's definitely been a pain point before.
